### ISSUE TITLE
undefined symbol ncclCommRegister

### ISSUE THREAD

**Issue by Unknown-Body** [VichyTong/CodeJudge#2]
when I pull the git and follow the instruction to install requirements, then acitvate the coda env and the error occurs.
![image](https://github.com/user-attachments/assets/e1047d30-03b1-42d9-add7-c4973cac154a)
How to sovle it?thx

**Comment by VichyTong** [comment]
Hi @zhilonglu,

Thank you for the attention to our work!

I'm happy to help you solve this question. Could you please tell me what is the cuda version and nvcc version on your server? Furthermore, it may be better to tell me the way you install the torch. As far as I know, this error usually happens when the cuda version is not consistent with the torch version.

Weixi

**Comment by Unknown-Body** [comment]
Thank you for kindly reply！
I check the version of pytorch and cuda, i found cu11 and cu12 related packages, and I check the CUDA version is 12.2.
So i modify the requirement.txt and remove the cu11 related package, then reinstall the conda environment.
Finally, succeed.

**Comment by VichyTong** [comment]
Hi @zhilonglu,

It's nice to hear you succeed :)
BTW, Would you mind to share the `requirements.txt` of the CUDA 12 version? I think many people use this version. If you are available, feel free to raise a pull request to upload the `cuda12_requirements.txt`.

Weixi
